// AIFeatureService.swift
// FlowDay
//
// AI-powered features for intelligent task management:
// 1. Smart Daily Planning — optimizes task scheduling based on energy levels
// 2. Natural Language Task Creation — parses free text into structured tasks
// 3. AI Task Breakdown — decomposes high-level goals into actionable subtasks
//
// All LLM calls go through ClaudeClient → Supabase Edge Function → Anthropic.
// The Anthropic API key lives server-side as a Supabase secret.
// The server applies prompt caching on each feature's stable system prompt.

import Foundation
import Observation

// MARK: - Data Models

/// Represents a daily plan generated by AI
struct SmartPlan: Codable {
    let scheduledTasks: [PlannedTask]
    let summary: String
    let tips: [String]
}

/// A task scheduled with timing and reasoning
struct PlannedTask: Codable {
    let taskTitle: String
    let suggestedTime: String // e.g., "9:00 AM"
    let reason: String
}

/// AI-extracted task details from natural language
struct AITaskSuggestion: Codable {
    let title: String
    let priority: Int // 1=urgent, 2=high, 3=medium, 4=low
    let dueDate: String? // ISO 8601 or null
    let scheduledTime: String? // HH:mm or null
    let estimatedMinutes: Int?
    let project: String?
    let labels: [String]
}

/// A breakdown of a goal into actionable subtasks
struct TaskBreakdown: Codable {
    let originalGoal: String
    let subtasks: [BreakdownItem]
    let projectSuggestion: String?
}

/// A single item in a task breakdown
struct BreakdownItem: Codable {
    let title: String
    let priority: Int // 1-4
    let estimatedMinutes: Int
    let reasoning: String
}

// MARK: - AIFeatureService

@Observable
final class AIFeatureService {
    static let shared = AIFeatureService()

    var isProcessing: Bool = false
    var lastError: String?

    private init() {}

    // MARK: - Feature 1: Smart Daily Planning

    /// Generate an optimized daily plan based on tasks, energy, and calendar availability
    func generateSmartPlan(
        tasks: [FDTask],
        energyLevel: EnergyLevel,
        calendarEvents: [String],
        freeSlots: [(start: Date, end: Date)]
    ) async throws -> SmartPlan {
        isProcessing = true
        defer { isProcessing = false }

        let taskDescriptions = tasks.map { task in
            "- \(task.title) (Priority: \(task.priority.label), Duration: \(task.estimatedMinutes ?? 30)min)"
        }.joined(separator: "\n")

        let slotsDescription = freeSlots.map { slot in
            let formatter = DateFormatter()
            formatter.timeStyle = .short
            let start = formatter.string(from: slot.start)
            let end = formatter.string(from: slot.end)
            return "- \(start) to \(end)"
        }.joined(separator: "\n")

        let calendarDescription = calendarEvents.isEmpty
            ? "No calendar events"
            : calendarEvents.joined(separator: ", ")

        let userMessage = """
        Please create an optimized daily plan with these constraints:

        Current Energy Level: \(energyLevel.label)

        Tasks to schedule:
        \(taskDescriptions)

        Available time slots:
        \(slotsDescription)

        Calendar events: \(calendarDescription)

        Return a JSON object with this exact structure:
        {
            "scheduledTasks": [
                {"taskTitle": "string", "suggestedTime": "HH:MM AM/PM", "reason": "string"}
            ],
            "summary": "brief overview string",
            "tips": ["tip1", "tip2", "tip3"]
        }
        """

        do {
            let response = try await ClaudeClient.shared.chat(
                feature: .flowAI,
                messages: [LLMMessage(role: .user, content: userMessage)],
                temperature: 0.5,
                maxTokens: 2048
            )

            if let plan = parseJSON(response, as: SmartPlan.self) {
                return plan
            } else {
                // Fallback parser for non-JSON responses
                return parseSmartPlanFallback(response)
            }
        } catch {
            lastError = "Failed to generate smart plan: \(error.localizedDescription)"
            throw error
        }
    }

    // MARK: - Feature 2: Natural Language Task Creation

    /// Parse natural language input into structured task details
    func parseTaskWithAI(input: String) async throws -> AITaskSuggestion {
        isProcessing = true
        defer { isProcessing = false }

        let userMessage = """
        Extract task details from this natural language input:
        "\(input)"

        Return a JSON object with this exact structure:
        {
            "title": "task title string",
            "priority": 2,
            "dueDate": "YYYY-MM-DD" or null,
            "scheduledTime": "HH:mm" or null,
            "estimatedMinutes": 30 or null,
            "project": "project name" or null,
            "labels": ["label1", "label2"]
        }

        Priority scale: 1=urgent, 2=high, 3=medium, 4=low
        Only include dates if explicitly mentioned or clearly implied.
        """

        do {
            let response = try await ClaudeClient.shared.chat(
                feature: .flowAI,
                messages: [LLMMessage(role: .user, content: userMessage)],
                temperature: 0.3,
                maxTokens: 512
            )

            if let suggestion = parseJSON(response, as: AITaskSuggestion.self) {
                return suggestion
            } else {
                // Fallback parser
                return parseTaskSuggestionFallback(response, originalInput: input)
            }
        } catch {
            lastError = "Failed to parse task: \(error.localizedDescription)"
            throw error
        }
    }

    // MARK: - Feature 3: AI Task Breakdown

    /// Break down a high-level goal into actionable subtasks
    func breakdownTask(goal: String, context: String? = nil) async throws -> TaskBreakdown {
        isProcessing = true
        defer { isProcessing = false }

        var userMessage = """
        Break down this goal into 5-7 actionable subtasks:
        "\(goal)"
        """

        if let context = context {
            userMessage += "\n\nAdditional context: \(context)"
        }

        userMessage += """

        Return a JSON object with this exact structure:
        {
            "originalGoal": "goal string",
            "subtasks": [
                {"title": "string", "priority": 2, "estimatedMinutes": 30, "reasoning": "string"}
            ],
            "projectSuggestion": "suggested project name" or null
        }

        Priority scale: 1=urgent, 2=high, 3=medium, 4=low
        Be realistic with time estimates.
        """

        do {
            let response = try await ClaudeClient.shared.chat(
                feature: .flowAI,
                messages: [LLMMessage(role: .user, content: userMessage)],
                temperature: 0.7,
                maxTokens: 2048
            )

            if let breakdown = parseJSON(response, as: TaskBreakdown.self) {
                return breakdown
            } else {
                // Fallback parser
                return parseTaskBreakdownFallback(response, originalGoal: goal)
            }
        } catch {
            lastError = "Failed to break down task: \(error.localizedDescription)"
            throw error
        }
    }

    // MARK: - JSON Parsing Helper

    /// Attempt to parse JSON from LLM response, handling markdown code blocks and extra text
    func parseJSON<T: Decodable>(_ text: String, as type: T.Type) -> T? {
        var jsonString = text

        // Remove markdown code blocks
        if let startIdx = jsonString.range(of: "```json") {
            jsonString.removeSubrange(...startIdx.lowerBound)
            if let endIdx = jsonString.range(of: "```") {
                jsonString.removeSubrange(endIdx.lowerBound..<jsonString.endIndex)
            }
        } else if let startIdx = jsonString.range(of: "```") {
            jsonString.removeSubrange(...startIdx.lowerBound)
            if let endIdx = jsonString.range(of: "```") {
                jsonString.removeSubrange(endIdx.lowerBound..<jsonString.endIndex)
            }
        }

        // Find JSON object boundaries
        guard let jsonStart = jsonString.firstIndex(of: "{"),
              let jsonEnd = jsonString.lastIndex(of: "}") else {
            return nil
        }

        let jsonSubstring = jsonString[jsonStart...jsonEnd]
        let cleanedJSON = String(jsonSubstring)

        do {
            let decoder = JSONDecoder()
            return try decoder.decode(type, from: cleanedJSON.data(using: .utf8) ?? Data())
        } catch {
            #if DEBUG
            print("[AIFeatureService] JSON decode error: \(error)")
            #endif
            return nil
        }
    }

    // MARK: - Fallback Parsers

    /// Fallback text parser for SmartPlan when JSON parsing fails
    private func parseSmartPlanFallback(_ text: String) -> SmartPlan {
        let lines = text.split(separator: "\n")

        let scheduledTasks: [PlannedTask] = []
        var summary = "Plan generated"
        var tips: [String] = []

        // Extract summary (usually in first few lines)
        if let summaryLine = lines.first(where: { $0.lowercased().contains("plan") || $0.lowercased().contains("summary") }) {
            summary = String(summaryLine).replacingOccurrences(of: "Summary:", with: "").trimmingCharacters(in: .whitespaces)
        }

        // Extract tips
        var inTips = false
        for line in lines {
            let trimmed = String(line).trimmingCharacters(in: .whitespaces)
            if trimmed.lowercased().contains("tip") {
                inTips = true
            } else if inTips && !trimmed.isEmpty && !trimmed.starts(with: "-") {
                inTips = false
            }
            if inTips && trimmed.starts(with: "-") {
                tips.append(trimmed.dropFirst().trimmingCharacters(in: .whitespaces))
            }
        }

        // Default tips if not found
        if tips.isEmpty {
            tips = ["Start with high-energy tasks", "Take breaks between focused sessions", "Review progress in the evening"]
        }

        return SmartPlan(
            scheduledTasks: scheduledTasks,
            summary: summary,
            tips: Array(tips.prefix(3))
        )
    }

    /// Fallback text parser for AITaskSuggestion when JSON parsing fails
    private func parseTaskSuggestionFallback(_ text: String, originalInput: String) -> AITaskSuggestion {
        let priority = text.lowercased().contains("urgent")
            ? 1
            : text.lowercased().contains("high")
            ? 2
            : text.lowercased().contains("medium")
            ? 3
            : 4

        let labels = extractLabels(from: text)

        return AITaskSuggestion(
            title: originalInput.split(separator: ",").first.map({ String($0).trimmingCharacters(in: .whitespaces) }) ?? originalInput,
            priority: priority,
            dueDate: extractDate(from: text),
            scheduledTime: extractTime(from: text),
            estimatedMinutes: extractDuration(from: text),
            project: nil,
            labels: labels
        )
    }

    /// Fallback text parser for TaskBreakdown when JSON parsing fails
    private func parseTaskBreakdownFallback(_ text: String, originalGoal: String) -> TaskBreakdown {
        let lines = text.split(separator: "\n")
        var subtasks: [BreakdownItem] = []

        // Extract basic subtasks from bullet points
        for line in lines {
            let trimmed = String(line).trimmingCharacters(in: .whitespaces)
            if trimmed.starts(with: "-") || trimmed.starts(with: "•") {
                let title = trimmed.dropFirst().trimmingCharacters(in: .whitespaces)
                subtasks.append(BreakdownItem(
                    title: String(title),
                    priority: 2,
                    estimatedMinutes: 30,
                    reasoning: "Extracted from goal breakdown"
                ))
            }
        }

        // Create default subtasks if none found
        if subtasks.isEmpty {
            subtasks = [
                BreakdownItem(title: "Research and planning", priority: 2, estimatedMinutes: 30, reasoning: "Foundation step"),
                BreakdownItem(title: "Setup and preparation", priority: 2, estimatedMinutes: 45, reasoning: "Necessary groundwork"),
                BreakdownItem(title: "Core work", priority: 1, estimatedMinutes: 120, reasoning: "Main effort"),
                BreakdownItem(title: "Review and refine", priority: 2, estimatedMinutes: 30, reasoning: "Quality check"),
                BreakdownItem(title: "Launch or finalize", priority: 2, estimatedMinutes: 20, reasoning: "Final step")
            ]
        }

        return TaskBreakdown(
            originalGoal: originalGoal,
            subtasks: subtasks,
            projectSuggestion: nil
        )
    }

    // MARK: - Text Extraction Helpers

    private func extractDate(from text: String) -> String? {
        let pattern = #"\d{1,2}[-/]\d{1,2}[-/]\d{2,4}"#
        if let regex = try? NSRegularExpression(pattern: pattern) {
            let range = NSRange(text.startIndex..<text.endIndex, in: text)
            if let match = regex.firstMatch(in: text, range: range) {
                if let range = Range(match.range, in: text) {
                    return String(text[range])
                }
            }
        }
        return nil
    }

    private func extractTime(from text: String) -> String? {
        let pattern = #"(\d{1,2}):(\d{2})\s?(AM|PM|am|pm)?"#
        if let regex = try? NSRegularExpression(pattern: pattern) {
            let range = NSRange(text.startIndex..<text.endIndex, in: text)
            if let match = regex.firstMatch(in: text, range: range) {
                if let range = Range(match.range, in: text) {
                    return String(text[range])
                }
            }
        }
        return nil
    }

    private func extractDuration(from text: String) -> Int? {
        let pattern = #"(\d+)\s*(min|minute|minutes|hour|hours)?"#
        if let regex = try? NSRegularExpression(pattern: pattern) {
            let range = NSRange(text.startIndex..<text.endIndex, in: text)
            let matches = regex.matches(in: text, range: range)
            for match in matches {
                if let numberRange = Range(match.range(at: 1), in: text) {
                    if let number = Int(text[numberRange]) {
                        if let unitRange = Range(match.range(at: 2), in: text) {
                            let unit = String(text[unitRange]).lowercased()
                            if unit.contains("hour") {
                                return number * 60
                            }
                            return number
                        }
                        return number
                    }
                }
            }
        }
        return nil
    }

    private func extractLabels(from text: String) -> [String] {
        var labels: [String] = []

        let labelPatterns = [
            ("work", ["work", "office", "job"]),
            ("personal", ["personal", "home"]),
            ("urgent", ["urgent", "asap", "critical"]),
            ("meeting", ["meeting", "call", "sync"]),
            ("review", ["review", "check", "approve"])
        ]

        for (label, keywords) in labelPatterns {
            for keyword in keywords {
                if text.lowercased().contains(keyword) {
                    labels.append(label)
                    break
                }
            }
        }

        return Array(Set(labels)).sorted()
    }
}
